main = ".open-next/worker.js"
name = "portfolio"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
